name: Bruno Vilela
favicon: null
layout_spectrum: 0.423641178291291
typography_spectrum: 0.09004967543296516
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefff9'
    - '#22231b'
    - '#a2886d'
    - '#77664c'
    - '#c5ae96'
  brandStrength: 0.4576818870846182
  lightness: 0.06773464940488338
  saturation: 0.8267051600851119
  rhythmicContrast: 0.13756319717504084
purpose: []
